"""add cascade delete to messages

Revision ID: 1fb3b5e0aa68
Revises: 2f9fc124b6de
Create Date: 2026-06-05 18:48:03.076848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb3b5e0aa68'
down_revision: Union[str, Sequence[str], None] = '2f9fc124b6de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('messages_room_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('room_members_room_id_fkey'), 'room_members', type_='foreignkey')
    op.create_foreign_key(None, 'room_members', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.create_foreign_key(op.f('room_members_room_id_fkey'), 'room_members', 'rooms', ['room_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_room_id_fkey'), 'messages', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
