"""Member-ccount

Revision ID: 2f9fc124b6de
Revises: 9cff1e51847c
Create Date: 2026-06-05 17:51:40.247733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9fc124b6de'
down_revision: Union[str, Sequence[str], None] = '9cff1e51847c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('member_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'member_count')
    # ### end Alembic commands ###
