"""add cascade delete to messages

Revision ID: d0a4f3d3bd88
Revises: 1fb3b5e0aa68
Create Date: 2026-06-05 18:51:03.389741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a4f3d3bd88'
down_revision: Union[str, Sequence[str], None] = '1fb3b5e0aa68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('message_receipts_message_id_fkey'), 'message_receipts', type_='foreignkey')
    op.create_foreign_key(None, 'message_receipts', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_receipts', type_='foreignkey')
    op.create_foreign_key(op.f('message_receipts_message_id_fkey'), 'message_receipts', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###
